apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: argocd
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: argocd-operatorgroup
  namespace: argocd
spec:
  targetNamespaces:
  - argocd
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acm-operator-subscription
  namespace: argocd
spec:
  sourceNamespace: openshift-marketplace
  source: community-operators
  channel: alpha
  installPlanApproval: Automatic
  name: argocd-operator
  startingCSV: argocd-operator.v{{ argocd_version }}
