{% set release =  '4.' + (tag|string).split('.')[1] if tag|count('.') > 1 else tag %}
{% set kcli_images = ["quay.io/karmab/curl:multi", "quay.io/karmab/origin-coredns:multi", "quay.io/karmab/haproxy:multi", "quay.io/karmab/origin-keepalived-ipfailover:multi", "quay.io/karmab/mdns-publisher:multi", "quay.io/karmab/kubectl:multi"] %}
{% if async|default(False) %}
{% do kcli_images.append("quay.io/karmab/kcli:latest") %}
{% endif %}

apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  platform:
    graph: false
{% if version in ['ci', 'nightly'] %}
{% set release = 'origin/release-scos:scos-%s' % tag if okd else 'registry.ci.openshift.org/ocp/release:%s' % tag %}
    release: registry.ci.openshift.org/{{ release }}
{% else %}
    channels:
    - name: {{ disconnected_channel or ('candidate' if 'rc' in tag else 'stable') }}-{{ release }}
{% if tag|count('.') > 1 %}
      minVersion: {{ (disconnected_extra_release or tag)|min_ocp_version(tag) }}
      maxVersion: {{ (disconnected_extra_release or tag)|max_ocp_version(tag) }}
{% endif %}
{% endif %}
    architectures:
#   - multi
    - amd64
  additionalImages:
{% for image in kcli_images + extra_images|default([]) %}
  - name: {{ image }}
{% endfor %}
{% set operators = disconnected_operators|default([]) + disconnected_certified_operators|default([]) + disconnected_community_operators|default([]) + disconnected_marketplace_operators|default([]) %}
{% if operators %}
  operators:
{% if disconnected_operators|default([]) %}
{% set catalog = 'quay.io/prega/prega-operator-index' if prega|default(False) else 'registry.redhat.io/redhat/redhat-operator-index' %}
  - catalog: {{ catalog }}:{{ disconnected_operators_version or release_tag or "v%s" % OPENSHIFT_TAG }}
    packages:
{% for package in disconnected_operators %}
{% if package.name is defined %}
    - name: {{ package.name }}
{% else %}{# Comment: Support old syntax #}
    - name: {{ package }}
{% endif %}
{% if package.minVersion is defined %}
      minVersion: {{ package.minVersion }}
{% endif %}
{% if package.maxVersion is defined %}
      maxVersion: {{ package.maxVersion }}
{% endif %}
{% if package.channels is defined and package.channels|length > 0 %}
      channels:
{% for channel in package.channels %}
      - name: {{ channel.name }}
{% if channel.minVersion is defined %}
        minVersion: {{ channel.minVersion }}
{% endif %}
{% if channel.maxVersion is defined %}
        maxVersion: {{ channel.maxVersion }}
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
{% endif %}
{% if disconnected_certified_operators|default([]) %}
  - catalog: registry.redhat.io/redhat/certified-operator-index:{{ disconnected_certified_operators_version or release_tag or "v%s" % OPENSHIFT_TAG }}
    packages:
{% for package in disconnected_certified_operators %}
{% if package.name is defined %}
    - name: {{ package.name }}
{% else %}
    - name: {{ package }}
{% endif %}
{% if package.minVersion is defined %}
      minVersion: {{ package.minVersion }}
{% endif %}
{% if package.maxVersion is defined %}
      maxVersion: {{ package.maxVersion }}
{% endif %}
{% if package.channels is defined and package.channels|length > 0 %}
      channels:
{% for channel in package.channels %}
      - name: {{ channel.name }}
{% if channel.minVersion is defined %}
        minVersion: {{ channel.minVersion }}
{% endif %}
{% if channel.maxVersion is defined %}
        maxVersion: {{ channel.maxVersion }}
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
{% endif %}
{% if disconnected_community_operators|default([]) %}
  - catalog: registry.redhat.io/redhat/community-operator-index:{{ disconnected_community_operators_version or release_tag or "v%s" % OPENSHIFT_TAG }}
    packages:
{% for package in disconnected_community_operators %}
{% if package.name is defined %}
    - name: {{ package.name }}
{% else %}
    - name: {{ package }}
{% endif %}
{% if package.minVersion is defined %}
      minVersion: {{ package.minVersion }}
{% endif %}
{% if package.maxVersion is defined %}
      maxVersion: {{ package.maxVersion }}
{% endif %}
{% if package.channels is defined and package.channels|length > 0 %}
      channels:
{% for channel in package.channels %}
      - name: {{ channel.name }}
{% if channel.minVersion is defined %}
        minVersion: {{ channel.minVersion }}
{% endif %}
{% if channel.maxVersion is defined %}
        maxVersion: {{ channel.maxVersion }}
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
{% endif %}
{% if disconnected_marketplace_operators|default([]) %}
  - catalog: registry.redhat.io/redhat/redhat-marketplace-index:{{ disconnected_marketplace_operators_version or release_tag or "v%s" % OPENSHIFT_TAG }}
    packages:
{% for package in disconnected_marketplace_operators %}
{% if package.name is defined %}
    - name: {{ package.name }}
{% else %}
    - name: {{ package }}
{% endif %}
{% if package.minVersion is defined %}
      minVersion: {{ package.minVersion }}
{% endif %}
{% if package.maxVersion is defined %}
      maxVersion: {{ package.maxVersion }}
{% endif %}
{% if package.channels is defined and package.channels|length > 0 %}
      channels:
{% for channel in package.channels %}
      - name: {{ channel.name }}
{% if channel.minVersion is defined %}
        minVersion: {{ channel.minVersion }}
{% endif %}
{% if channel.maxVersion is defined %}
        maxVersion: {{ channel.maxVersion }}
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
{% endif %}
{% endif %}
{% if disconnected_extra_catalogs|default([]) %}
{% for catalog_image in disconnected_extra_catalogs %}
  - catalog: {{ catalog_image }}
{% endfor %}
{% endif %}
