apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: {{ namespace }}
spec:
  manageNodes: false
  monDataDirHostPath: /var/lib/rook
  storageDeviceSets:
  - count: {{ ocs_devicesets }}
    dataPVCTemplate:
      spec:
        accessModes:
        - {{ ocs_accessmode }}
        resources:
          requests:
            storage: {{ ocs_disksize }}Gi
        storageClassName: {{ ocs_storageclass }}
        volumeMode: Block
    name: ocs-deviceset
    portable: {{ ocs_portable }}
    replica: {{ ocs_replicas or 3 }}
