apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: {{ namespace }}
spec:
  BareMetalPlatform: true
  infra:
    nodePlacement:
      nodeSelector:
        node-role.kubernetes.io/{{ kubevirt_infra }}: ""
      tolerations:
      - effect: NoSchedule
        key: "node-role.kubernetes.io/{{ kubevirt_infra }}"
        operator: Exists
  workloads:
    nodePlacement:
      nodeSelector:
        node-role.kubernetes.io/{{ kubevirt_workloads }}: ""
      tolerations:
      - effect: NoSchedule
        key: "node-role.kubernetes.io/{{ kubevirt_workloads }}"
        operator: Exists
