export OPENSHIFT_INSTALL_PLATFORM=libvirt
export OPENSHIFT_INSTALL_BASE_DOMAIN=tt.testing
export OPENSHIFT_INSTALL_CLUSTER_NAME=testk
export OPENSHIFT_INSTALL_PULL_SECRET_PATH=/root/coreos_pull.json
export OPENSHIFT_INSTALL_LIBVIRT_URI=qemu+ssh://root@192.168.122.1/system
export OPENSHIFT_INSTALL_LIBVIRT_IMAGE=http://192.168.122.1/rhcos.qcow2.qemu
export OPENSHIFT_INSTALL_EMAIL_ADDRESS=admin@magnifico.es
export OPENSHIFT_INSTALL_PASSWORD=password
