apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
{% if not mce_ha_config %}
  availabilityConfig: Basic
{% endif %}
  overrides:
    components:
    - name: hypershift
      enabled: {{ mce_hypershift }}
    - name: siteconfig
      enabled: {{ mce_siteconfig }}
