apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: sushy
  name: sushy
  namespace: openshift-kcli-infra
spec:
  host: sushy.apps.{{ cluster }}.{{ domain }}
  port:
    targetPort: 8000
  to:
    kind: Service
    name: sushy
    weight: 100
  wildcardPolicy: None
