---
kind: Pod
apiVersion: v1
metadata:
  name: coredns
  namespace: kcli-infra
  creationTimestamp:
  deletionGracePeriodSeconds: 65
  labels:
    app: kcli-coredns
spec:
  volumes:
  - name: conf-dir
    hostPath:
      path: "/etc/kubernetes"
  initContainers:
  - name: update-coredns-conf
    securityContext:
      privileged: true
    image: {{ disconnected_url if disconnected_url != None else 'quay.io' }}/karmab/curl:{{ arch_tag }}
    command:
    - "/bin/sh"
    - "-c"
    - |
      #/bin/sh
      NAMESERVER=$(grep nameserver /etc/resolv.conf | grep -v 'fe80::' | tail -1 | sed 's/nameserver //')
      [ "$NAMESERVER" == "" ] && exit 1
      [ ! -f /etc/coredns/Corefile ] && [ -f /etc/coredns/Corefile.template ] && cp /etc/coredns/Corefile.template /etc/coredns/Corefile
      grep -q "NAMESERVER" /etc/coredns/Corefile || exit 0
      sed -i "s@NAMESERVER@$NAMESERVER@" /etc/coredns/Corefile
      {% if sno_dns %}
      {% if ipv6 %}
      NIC=$(ip -6 r | grep -v lo | head -1 | awk '{print $3}')
      IP=$(ip -6 -o addr show $NIC | awk '{print $4}' | cut -d "/" -f 1 | head -1)
      {% else %}
      NIC=$(ip r | grep default | head -1 | awk '{print $5}')
      IP=$(ip -o addr show $NIC | awk '{print $4}' | cut -d "/" -f 1 | head -1)
      {% endif %}
      sed -i "s@None@$IP@" /etc/coredns/Corefile
      {% endif %}
    resources: {}
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/coredns"
    imagePullPolicy: IfNotPresent
  containers:
  - name: coredns
    securityContext:
      privileged: true
    image: {{ disconnected_url if disconnected_url != None else 'quay.io' }}/karmab/origin-coredns:{{ arch_tag }}
    args:
    - "--conf"
    - "/etc/coredns/Corefile"
    resources:
      requests:
        cpu: 150m
        memory: 512Mi
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/coredns"
    readinessProbe:
      httpGet:
        path: /health
        port: 18080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
      timeoutSeconds: 10
    livenessProbe:
      httpGet:
        path: /health
        port: 18080
        scheme: HTTP
      initialDelaySeconds: 60
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
    terminationMessagePolicy: FallbackToLogsOnError
    imagePullPolicy: IfNotPresent
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
