---
kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: openshift-infra
  creationTimestamp:
  deletionGracePeriodSeconds: 65
  labels:
    app: kcli-nginx
spec:
  volumes:
  - name: data-dir
    empty-dir: {}
  - name: conf-dir
    hostPath:
      path: "/etc/kubernetes"
  initContainers:
  - name: nginx-get-ctlplane-mco
    securityContext:
      privileged: true
    image: {{ disconnected_url if disconnected_url != None else 'docker.io' }}/karmab/curl
    command:
    - "curl"
    args:
    - "-gkL"
    - "-H"
    - "{{ curl_header }}"
{%- if ipv6 %}
    - "https://[{{ api_ip}}]:22623/config/ctlplane"
{%- else %}
    - "https://{{ api_ip}}:22623/config/ctlplane"
{%- endif %}
    - "-o"
    - "/usr/share/nginx/html/ctlplane"
    volumeMounts:
    - name: data-dir
      mountPath: "/usr/share/nginx/html"
    - name: conf-dir
      mountPath: "/etc/nginx"
  containers:
  - name: nginx
    image: {{ disconnected_url if disconnected_url != None else 'docker.io' }}/library/nginx:alpine
    resources:
      requests:
        cpu: 150m
        memory: 1024Mi
    volumeMounts:
    - name: data-dir
      mountPath: "/usr/share/nginx/html"
    - name: conf-dir
      mountPath: "/etc/nginx"
    terminationMessagePolicy: FallbackToLogsOnError
    imagePullPolicy: IfNotPresent
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
