apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  capacity:
    storage: {{ nfs_pv_size }}Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /pv001
    server: IP
  persistentVolumeReclaimPolicy: Recycle
