#!/bin/bash

CLUSTER={{ cluster }}
DOMAIN={{ domain }}

[ "$(hostname -s)" == "{{ cluster }}-bootstrap" ] || which crictl >/dev/null 2>&1
if [ "$?" != "0" ] ; then
  exit 0
fi

if [ "$(grep '# kcli' /etc/resolv.conf)" == "" ] ; then
  sleep 2
  NIC={{ "$(ip -6 r | grep -v lo | head -1 | grep -oP '(?<=dev )[^ ]*')" if ipv6 else "$(ip r | grep default | head -1 | grep -oP '(?<=dev )[^ ]*')" }}
  IP={{ "$(ip -o -f inet6 addr show $NIC | head -1 | grep -oP '(?<=inet6 )[^ ]*' | cut -d '/' -f 1)" if ipv6 else "$(ip -o -f inet addr show $NIC | head -1 | grep -oP '(?<=inet )[^ ]*' | cut -d '/' -f 1)" }}
  sed -i "s/$CLUSTER.$DOMAIN//" /etc/resolv.conf
  sed -i "s/search /search $CLUSTER.$DOMAIN /" /etc/resolv.conf
  sed -i "0,/nameserver/s/nameserver/nameserver $IP # kcli\n&/" /etc/resolv.conf
fi
