apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  defaultNetwork:
    type: OVNKubernetes
    ovnKubernetesConfig:
      mtu: {{ 1354 if ipsec else mtu }}
{% if ipsec or mode != None %}
{% if mode != None %}
      ipsecConfig:
        mode: {{ mode }}
{% else %}
      ipsecConfig: {}
{% endif %}
{% endif %}
{% if ovn_hostrouting or relocate %}
      gatewayConfig:
        routingViaHost: true
{% endif %}
