apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-kcli
  namespace: default
  labels:
    app: httpd-kcli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-kcli
  template:
    metadata:
      labels:
        app: httpd-kcli
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      containers:
        - name: httpd
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
          image: registry.redhat.io/rhel8/httpd-24
          ports:
          - containerPort: 8080
          securityContext:
           runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-kcli-svc
  namespace: default
  labels:
    app: httpd-kcli
spec:
  type: NodePort
  selector:
    app: httpd-kcli
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
