apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: sno-custom
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
{% for file in files %}
        - contents:
            source: data:text/plain;charset=utf-8;base64,{{ file['data']|base64 }}
            verification: {}
          mode: {{ file['mode']|default(420) }}
          path: {{ file['path'] }}
{% endfor %}
