apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoapprover
  namespace: openshift-infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoapprover
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: autoapprover
  namespace: openshift-infra
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: autoapprover
  namespace: openshift-infra
spec:
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        spec:
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
            operator: Exists
          containers:
          - command:
            - "/bin/sh"
            - "-c"
            - |
              #!/bin/sh
              for cert in $(kubectl get csr -o name) ; do
                kubectl certificate approve $cert
              done
            image: {{ disconnected_url if disconnected_url != None else 'quay.io' }}/karmab/kubectl:{{ arch_tag }}
            imagePullPolicy: Always
            name: autoapprover
          restartPolicy: OnFailure
          serviceAccountName: autoapprover
  schedule: '*/2 * * * *'
