calicoassets = ['crds/01-crd-installation.yaml',
                'crds/01-crd-tigerastatus.yaml',
                'crds/calico/kdd/02-crd-bgpconfiguration.yaml',
                'crds/calico/kdd/02-crd-bgppeer.yaml',
                'crds/calico/kdd/02-crd-blockaffinity.yaml',
                'crds/calico/kdd/02-crd-clusterinformation.yaml',
                'crds/calico/kdd/02-crd-felixconfiguration.yaml',
                'crds/calico/kdd/02-crd-globalnetworkpolicy.yaml',
                'crds/calico/kdd/02-crd-globalnetworkset.yaml',
                'crds/calico/kdd/02-crd-hostendpoint.yaml',
                'crds/calico/kdd/02-crd-ipamblock.yaml',
                'crds/calico/kdd/02-crd-ipamconfig.yaml',
                'crds/calico/kdd/02-crd-ipamhandle.yaml',
                'crds/calico/kdd/02-crd-ippool.yaml',
                'crds/calico/kdd/02-crd-kubecontrollersconfiguration.yaml',
                'crds/calico/kdd/02-crd-networkpolicy.yaml',
                'crds/calico/kdd/02-crd-networkset.yaml',
                'tigera-operator/00-namespace-tigera-operator.yaml',
                'tigera-operator/02-rolebinding-tigera-operator.yaml',
                'tigera-operator/02-role-tigera-operator.yaml',
                'tigera-operator/02-serviceaccount-tigera-operator.yaml',
                'tigera-operator/02-configmap-calico-resources.yaml',
                'tigera-operator/02-configmap-tigera-install-script.yaml',
                'tigera-operator/02-tigera-operator.yaml',
                '01-cr-installation.yaml']
calicoassets = ['https://docs.projectcalico.org/manifests/ocp/%s' % asset for asset in calicoassets]
