calicoassets = ['crds/01-crd-installation.yaml',
                'crds/01-crd-imageset.yaml',
                'crds/01-crd-tigerastatus.yaml',
                'crds/calico/kdd/crd.projectcalico.org_bgpconfigurations.yaml',
                'crds/calico/kdd/crd.projectcalico.org_bgppeers.yaml',
                'crds/calico/kdd/crd.projectcalico.org_blockaffinities.yaml',
                'crds/calico/kdd/crd.projectcalico.org_clusterinformations.yaml',
                'crds/calico/kdd/crd.projectcalico.org_felixconfigurations.yaml',
                'crds/calico/kdd/crd.projectcalico.org_globalnetworkpolicies.yaml',
                'crds/calico/kdd/crd.projectcalico.org_globalnetworksets.yaml',
                'crds/calico/kdd/crd.projectcalico.org_hostendpoints.yaml',
                'crds/calico/kdd/crd.projectcalico.org_ipamblocks.yaml',
                'crds/calico/kdd/crd.projectcalico.org_ipamconfigs.yaml',
                'crds/calico/kdd/crd.projectcalico.org_ipamhandles.yaml',
                'crds/calico/kdd/crd.projectcalico.org_ippools.yaml',
                'crds/calico/kdd/crd.projectcalico.org_kubecontrollersconfigurations.yaml',
                'crds/calico/kdd/crd.projectcalico.org_networkpolicies.yaml',
                'crds/calico/kdd/crd.projectcalico.org_networksets.yaml',
                'tigera-operator/00-namespace-tigera-operator.yaml',
                'tigera-operator/02-rolebinding-tigera-operator.yaml',
                'tigera-operator/02-role-tigera-operator.yaml',
                'tigera-operator/02-serviceaccount-tigera-operator.yaml',
                'tigera-operator/02-configmap-calico-resources.yaml',
                'tigera-operator/02-tigera-operator.yaml',
                '01-cr-installation.yaml']
calicoassets = ['https://docs.projectcalico.org/manifests/ocp/%s' % asset for asset in calicoassets]
