---
kind: Pod
apiVersion: v1
metadata:
  name: keepalived
  namespace: openshift-infra
  creationTimestamp:
  deletionGracePeriodSeconds: 65
  labels:
    app: kcli-keepalived
spec:
  volumes:
  - name: conf-dir
    hostPath:
      path: "/etc/kubernetes"
  initContainers:
  - name: fix-keepalived-conf
    securityContext:
      privileged: true
    image: {{ disconnected_url if disconnected_url != None else 'quay.io' }}/karmab/curl:{{ arch_tag }}
    command:
    - "/bin/sh"
    - "-c"
    - |
      #/bin/sh
      grep "{{ ingress_ip }}/" /etc/keepalived/keepalived.conf
      if [ "$?" == "0" ] ; then
        exit 0
      else
        {% if ipv6 %}
        NIC=$(ip -6 r | grep -v lo | head -1 | sed 's/.*dev \(.*\) \(proto\|metric\).*/\1/' | awk '{print $1}')
        IP=$(ip -6 -o addr show $NIC | awk '{print $4}' | cut -d "/" -f 1 | head -1)
        NETMASK=$(ip -o -f inet6 addr show | grep $IP | sed "s@.*$IP/\(.*\) scope.*@\1@")
        {% else %}
        NIC=$(ip r | grep default | head -1 | sed 's/.*dev \(.*\) \(proto\|metric\).*/\1/')
        NETMASK=$(ip -o -f inet addr show | awk '/scope global/ {print $4}' | head -1 | cut -d'/' -f2)
        {% endif %}
        sed -i "s@NIC@$NIC@" /etc/keepalived/keepalived.conf
        if [ "$NETMASK" != "" ] ; then
          sed -i "s@{{ ingress_ip }}@{{ ingress_ip }}/$NETMASK@" /etc/keepalived/keepalived.conf
        fi
      fi
    resources: {}
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/keepalived"
    imagePullPolicy: IfNotPresent
  containers:
  - name: keepalived
    securityContext:
      privileged: true
    image: {{ disconnected_url if disconnected_url != None else 'quay.io' }}/karmab/origin-keepalived-ipfailover:{{ arch_tag }}
    command:
    - /usr/sbin/keepalived
    args:
    - "-f"
    - "/etc/keepalived/keepalived.conf"
    - "--dont-fork"
    - "--vrrp"
    - "--log-detail"
    - "--log-console"
    resources:
      requests:
        cpu: 150m
        memory: 2048Mi
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/keepalived"
    terminationMessagePolicy: FallbackToLogsOnError
    imagePullPolicy: IfNotPresent
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
