apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: {{ localstorage_name }}
  namespace: {{ namespace }}
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
{% if not localstorage_nodes %}
{% set localstorage_nodes = 99|defaultnodes(cluster, domain, masters,workers) %}
{% endif %}
{% for node in localstorage_nodes %}
          - {{ node }}
{% endfor %}
  storageClassDevices:
    - storageClassName: {{ localstorage_storageclass }}
      volumeMode: {{ localstorage_volumemode | capitalize }}
      fsType: {{ localstorage_fstype }}
      devicePaths:
{% for disk in localstorage_disks %}
      - /dev/{{ disk | replace('/dev/', '') }}
{% endfor %}
