apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: {{ namespace }}
spec:
  imagePullSecret: open-cluster-management-image-pull-credentials
  disableHubSelfManagement: {{ acm_disable_hub }}
