---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sushy
  name: sushy
  namespace: kcli-infra
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: sushy
