---
kind: Pod
apiVersion: v1
metadata:
  name: keepalived
  namespace: kcli-infra
  creationTimestamp:
  deletionGracePeriodSeconds: 65
  labels:
    app: kcli-keepalived
spec:
  volumes:
  - name: conf-dir
    hostPath:
      path: "/etc/kubernetes"
  initContainers:
  - name: fix-keepalived-conf
    securityContext:
      privileged: true
    image: {{ disconnected_url if disconnected_url != None else 'quay.io' }}/karmab/curl:multi
    command:
    - "/bin/sh"
    - "-c"
    - |
      #/bin/sh
      [ ! -f /etc/keepalived/keepalived.conf ] && [ -f /etc/keepalived/keepalived.conf.template ] && cp /etc/keepalived/keepalived.conf.template /etc/keepalived/keepalived.conf
      grep "{{ api_ip }}/" /etc/keepalived/keepalived.conf
      if [ "$?" == "0" ] ; then
        exit 0
      else
        {% if ipv6 %}
        NIC=$(ip -6 r | grep -v lo | head -1 | grep -oP '(?<=dev )[^ ]*')
        NETMASK=$(ip -o -f inet6 addr show $NIC | head -1 | grep -oP '(?<=inet6 )[^ ]*' | cut -d "/" -f 2)
        {% if name != cluster + '-bootstrap' %}
        NIC=br-ex
        {% endif %}
        {% else %}
        NIC=$(ip r | grep {{ baremetal_cidr or 'default' }} | head -1 | grep -oP '(?<=dev )[^ ]*')
        NETMASK=$(ip -o -f inet addr show $NIC | head -1 | grep -oP '(?<=inet )[^ ]*' | cut -d "/" -f 2)
        {% endif %}
        sed -i "s@NIC@$NIC@" /etc/keepalived/keepalived.conf
        if [ "$NETMASK" != "" ] ; then
          sed -i "s@{{ api_ip }}@{{ api_ip }}/$NETMASK@" /etc/keepalived/keepalived.conf
          {% if ingress_ip != None %}
          sed -i "s@{{ ingress_ip }}@{{ ingress_ip }}/$NETMASK@" /etc/keepalived/keepalived.conf
          {% endif %}
        fi
      fi
    resources: {}
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/keepalived"
    imagePullPolicy: IfNotPresent
  containers:
  - name: keepalived
    securityContext:
      privileged: true
    image: {{ disconnected_url if disconnected_url != None else 'quay.io' }}/karmab/origin-keepalived-ipfailover:multi
    command:
    - /usr/sbin/keepalived
    args:
    - "-f"
    - "/etc/keepalived/keepalived.conf"
    - "--dont-fork"
    - "--vrrp"
    - "--log-detail"
    - "--log-console"
    resources:
      requests:
        cpu: 150m
        memory: 2048Mi
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/keepalived"
    terminationMessagePolicy: FallbackToLogsOnError
    imagePullPolicy: IfNotPresent
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
