apiVersion: "kcli.karmalabs.local/v1"
kind: Plan
metadata:
  name: simpleplan2
spec:
  plan: |
    vm11:
      memory: 512
      numcpus: 2
      nets:
       - default
      template: cirros-0.4.0-x86_64-disk.img
    vm22:
      memory: 1024
      numcpus: 4
      nets:
       - default
      disks:
       - 20
      pool: default
      template: cirros-0.4.0-x86_64-disk.img
      cmds:
       - echo this stuff works > /tmp/result.txt
