---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-storage
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-storage-operatorgroup
  namespace: openshift-storage
spec:
  targetNamespaces:
  - openshift-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocs-operator
  namespace: openshift-storage
spec:
  sourceNamespace: openshift-marketplace
  source: {{ catalog | default('redhat-operators') }}
  startingCSV: ocs-operator.v{{ ocs_version }}
  channel: {{ ocs_channel }}
  installPlanApproval: Automatic
  name: ocs-operator
