apiVersion: v1
kind: Namespace
metadata:
  name: {{ namespace }}-{{ cluster }}
---
apiVersion: v1
data:
 .dockerconfigjson: {{ pull_secret|default('')|base64 }}
kind: Secret
metadata:
  name: {{ cluster }}-pull-secret
  namespace: {{ namespace }}-{{ cluster }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ cluster }}-ssh-key
  namespace: {{ namespace }}-{{ cluster }}
stringData:
  id_rsa.pub: {{ pub_key|default('') }}
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: capi-provider-role
  namespace: {{ namespace }}-{{ cluster }}
rules:
- apiGroups:
  - agent-install.openshift.io
  resources:
  - agents
  verbs:
  - '*'
---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: {{ cluster }}
  namespace: {{ namespace }}-{{ cluster }}
spec:
  pullSecretRef:
    name: {{ cluster }}-pull-secret
  sshAuthorizedKey: {{ pub_key }}
  agentLabels:
    cluster-name: {{ namespace }}-{{ cluster }}
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: {{ namespace }}-{{ cluster }}
---
