heat_template_version: 2014-10-16

description: >
  Post Configuration

parameters:
  servers:
    type: json
  param1:
    type: string
  param2:
    type: string

resources:
  ExtraConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: PARAM1
        - name: PARAM2
      config: {get_file: /home/stack/templates/environments/postconfig.sh}

  ExtraDeployments:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: ExtraConfig}
      actions: ['CREATE','UPDATE']
      input_values:
        PARAM1: {get_param: param1}
        PARAM2: {get_param: param2}
