apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kcli-pool
  namespace: metallb-system
spec:
  addresses:
{% for metallb_range in metallb_ranges %}
  - {{ metallb_range }}
{% endfor %}
