FROM centos:7
MAINTAINER Karim Boumedhel <karimboumedhel@gmail.com>

# Group the package installation
RUN yum clean all && \
    yum -y install epel-release && \
    yum -y install gcc libvirt-devel python-devel genisoimage qemu-kvm nmap-ncat python-pip openssh-clients && \
    yum clean all

# Group the pip installation
RUN pip install --no-cache-dir kcli docker

VOLUME ["/var/run/libvirt", "/root/.ssh", "/root"]

ENTRYPOINT ["/usr/bin/kcli"]
CMD ["-h"]
