  
FROM alpine:3.8

MAINTAINER Karim Boumedhel <karimboumedhel@gmail.com>

LABEL name="karmab/kubectl" \
      maintainer="karimboumedhel@gmail.com" \
      vendor="Karmalabs" \
      version="latest" \
      release="1" \
      summary="kubectl in a container" \
      description="kubectl in a container"

# curl -LO https://dl.k8s.io/release/v1.19.0/bin/linux/amd64/kubectl > kubectl
ADD kubectl /usr/local/bin/kubectl

RUN chmod 777 /usr/local/bin/kubectl
