name: SNAPSHOT
#on:
#  schedule:
#    - cron: '0 0 1 1,4,7,10 *'

on:
  workflow_dispatch:

env:
 QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
 QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
 PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
 PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
 DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
 DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
 CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
 COPR_BASE64: ${{ secrets.COPR_BASE64 }}
 PYTHONUNBUFFERED: true

jobs:

  run-workflow:
    name: Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo .github/prep.sh
        shell: bash
      - name: Lint Code
        run: .github/linting.sh
        shell: bash
      - name: Test code
        run: .github/testing.sh
        shell: bash
      - if: github.ref == 'refs/heads/main' && github.repository_owner == 'karmab'
        name: Snapshot RPM
        run: .github/copr_snapshot.sh
        shell: bash
      - if: github.ref == 'refs/heads/main' && github.repository_owner == 'karmab'
        name: Snapshot DEB
        run: .github/cloudsmith_snapshot.sh
        shell: bash
      - if: github.ref == 'refs/heads/main' && github.repository_owner == 'karmab'
        name: Snapshot Container
        run: .github/container_snapshot.sh
        shell: bash
