name: SNO-NIGHTLY-CI
on:
  schedule:
    - cron: '01 21 * * *'

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 CLUSTER: ci-sno
 PULLSECRET: /root/openshift_pull.json
 PARAMFILE: openshift-ci-paramfiles/sno.yml
 VERSION: stable
 TAG: "4.17"

jobs:
 requirements:
   if: github.repository == 'karmab/kcli'
   runs-on: u08
   steps:
    - uses: actions/checkout@v2
    - run: git pull origin ${GITHUB_REF##*/}
    - name: Install kcli
      run: |
        curl https://raw.githubusercontent.com/karmab/kcli/main/install.sh | bash
        kcli create sushy-service
    - name: Delete old install
      run: kcli -C local delete cluster --yes $CLUSTER || true

 deploy-baremetal-like-vm:
   needs: requirements
   runs-on: u08
   steps:
   - name: Deploy Baremetal like vm
     run: |
       kcli -C local create vm -P uefi=true -P boot_order=true -P start=false -P memory=32768 -P numcpus=16 -P disks=[50,100] -P nets=[baremetalfake] -P plan=$CLUSTER -P kube=$CLUSTER -P kubetype=openshift $CLUSTER

 deploy-openshift:
   needs: deploy-baremetal-like-vm
   runs-on: u08
   steps:
   - name: Deploy SNO
     run: |
       kcli create cluster openshift --paramfile $PARAMFILE -P pull_secret=$PULLSECRET -P version=$VERSION -P tag="$TAG" -P sno_disk=vdb $CLUSTER

# clean-up:
#   needs: deploy-openshift
#   runs-on: u08
#   steps:
#   - name: Clean everything after success
#     run: kcli -C local delete plan --yes $CLUSTER
