name: SNO-NIGHTLY-CI
on:
  schedule:
    - cron: '01 0 * * *'

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 PLAN: ci-sno
 PULLSECRET: /root/openshift_pull.json
 PARAMFILE: openshift-ci-paramfiles/sno.yml
 VERSION: stable
 TAG: "4.11"

jobs:
 requirements:
   runs-on: libvirt
   steps:
    - uses: actions/checkout@v2
    - run: git pull origin ${GITHUB_REF##*/}
    - name: Install kcli
      run: curl https://raw.githubusercontent.com/karmab/kcli/main/install.sh | bash
    - name: Delete old install
      run: kcli delete cluster --yes $PLAN || true

 deploy-openshift:
   needs: requirements
   runs-on: libvirt
   steps:
   - name: Deploy SNO
     run: |
       kcli create cluster openshift --paramfile $PARAMFILE -P pull_secret=$PULLSECRET -P version=$VERSION -P tag="$TAG" $PLAN

 clean-up:
   needs: deploy-openshift
   runs-on: libvirt
   steps:
   - name: Clean everything after success
     run: |
       kcli delete plan --yes $PLAN
